### ISSUE TITLE
Lack of documentation

### ISSUE THREAD

**Issue by Danct12** [Martchus/arch-repo-manager#1]
I noticed there's a lack of documentation, but I was able to figure everything out and was able to get it running.

Is there any plan for proper documentation? I'm planning to write some documentation and try my best to explain what they do.

**Comment by Martchus** [comment]
There's no plan to anything in this project. When I started this in 2017 or so this was mainly a playground for C++ programming and since then I have just extended things as needed.

The README *is* the documentation although it is probably more my personal notes. Improvements are welcome and I can also answer specific questions. The code also contains many comments so generating the API documentation via Doxygen is probably also not completely in vain (a CMake target exists for that).

There are also a few caveats that should probably be mentioned in the README:

* So far releases are not regularly tagged. It is probably best to build as latest version from Git as needed.
* 32-bit architectures are also not supported (as the database needs a huge address space).
* So far also no security review of the code has been done and at the same time the code base contains lots of rather low-level code, many parsers and a web service. So use this at your own risk (like most other open source projects, but here I'd like to highlight it specifically).
